### ISSUE TITLE
We Need A Slack or Mailing List

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#1]
@devgianlu,

I'm onboard with it. I've always wanted to do something like this....kinda like how Matt Mullenwag and Mike Little started WordPress. 

That said, we need a place for all of us developing and contributing to the project to have a place to co-ordinate. Slack, Discord, a mailing list, or anything would work. The university's ACM chapter uses a Discord server for all their co-ordination, but wherever else you can get interested folks to congregate in a single place works great too, whether it be a Slack, Telegram, or even a GNU Mailman mailing list. Hell, I could use the christoffen.com host to setup a mailing list if needed. 

I am definitely interested in working on the UX and UI portions if you're doing the backend (because I don't have a damn clue about how the backend works, Java isn't really my forte but I'll figure it out). 

I didn't think I'd be working alongside others on this project, but happy to join!

**Comment by devgianlu** [comment]
Discord is fine for me.

**Comment by MGageMorgan** [comment]
@devgianlu Should we start a server? That way, live responses can happen, while longer stuff goes here in the tracker.

**Comment by devgianlu** [comment]
Fine, create it.

**Comment by retnikt** [comment]
Is there an invite link (here from devRant btw)?

**Comment by devgianlu** [comment]
@retnikt https://discord.gg/xFCjsvB

**Comment by MGageMorgan** [comment]
@retnikt i recognize you lol

**Comment by MGageMorgan** [comment]
Because we now have a regular place for this stuff, I'm closing this issue.
