### ISSUE TITLE
Facebook/Twitter/GitHub/G+ Integration

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#10]
Users should be able to log in with their social media accounts.

**Comment by devgianlu** [comment]
Google: https://developers.google.com/identity/sign-in/web/

Facebook: https://developers.facebook.com/docs/facebook-login/web

Twitter: https://dev.twitter.com/web/sign-in/implementing

**Comment by devgianlu** [comment]
Keeping #80 instead.
