### ISSUE TITLE
Issues adding multiple Cardcast packs

### ISSUE THREAD

**Issue by EpicnessTwo** [devgianlu/PYX-Reloaded#105]
The initial Cardcast pack works fine when adding, adding a second pack doesn't do anything though. There is no errors in the console or in the browser. I have however recorded a video of this occurring. 

I'm using the latest code in the master branch: https://i.epickitty.co.uk/ss/e56a8508581.mp4

**Comment by devgianlu** [comment]
Issue is fixed in the latest version.
