### ISSUE TITLE
Make repository standalone

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/PYX-Reloaded#16]
We have already done a lot of work and the differences with the original fork are more than I expected. We should make this a standalone repository. In order to do that I need to contact the support, so I'll wait for approval.

https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

@MGageMorgan

**Comment by MGageMorgan** [comment]
@devgianlu will our commits still be attributed to us? Also because you contacted support during business hours, this may actually be done soon! Lmao

**Comment by devgianlu** [comment]
No I didn't contact them yet, I'll do it now. I'll ask for the commits thing, but I think everything will be the same.

**Comment by devgianlu** [comment]
@MGageMorgan The fork has now been detached, how should we rename this repo?
