### ISSUE TITLE
Add "Never" option to time-multiplier

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#22]
@devgianlu My friend just tested this out today and got hype af when he saw the Cardcast decks. 

He pointed out that the intervals were weird and that there was no option for "Never" - we set this to prevent getting banned when one of us has to go do something momentarily. 

I don't know enough about the server to know where this is at, and I start my first day tomorrow and the stress is so real...

**Comment by devgianlu** [comment]
@mgage "Unlimited" is missing, ops

**Comment by devgianlu** [comment]
@mgage "Unlimited" is missing, ops

**Comment by devgianlu** [comment]
Fixed with 6810c9474b820844b7bb9ffb4cb3ef9af07c78d6.
