### ISSUE TITLE
"Browse" Option for Cardcast

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#23]
@devgianlu,

Is it possible to keep in the ability to add the Cardcast code yourself but have a button titled "Browse" somewhere in the Cardcast section? If so, can it open a second dialog over the one that's already open? 

If we can do that, we could add in a browsing feature similar to the app. It looks fucking sexy, I like where this project is going. Either 1/12 or 1/13 will be the next time I'll be able to sit down and really look at what's going on. If you don't feel like adding it in the meantime, I'll mock it up over the weekend.

### **TODO**
- [x] Search
- [x] Filter
- [x] Sort
- [x] Pagination 
- [x] Toggle NSFW

**Comment by devgianlu** [comment]
Started developing in a separated branch: d730d65cdd492d3a8b37e7fa2ebc14b3d676626c

**Comment by devgianlu** [comment]
To be done: 
- [ ] Search
- [ ] Filter
- [ ] Sort
- [ ] Pagination

**Comment by devgianlu** [comment]
I cannot fit a text field inside the toolbar nor put a text field inside a menu for the search functionality. We'll need another solution. 

@MGageMorgan
