### ISSUE TITLE
Put "PYX Cards" toggles/labels into a grid similar to dropdowns in "General"

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#24]
Currently, it's a really long list. To try to mitigate the amount of time spent looking for a deck, we should try to get the the toggles/labels into a similar situation as the dropdowns in "General."

**Comment by devgianlu** [comment]
We can try putting checkboxes (the real ones, not switches) inside the select menu.

**Comment by MGageMorgan** [comment]
@devgianlu That's not what I meant at all, but that could really slim down the "Create Game" dialog! Could we use the checkboxes MDC provides? 

Also, another question: Could we add a "Search" field at the top of the select menu (example: Display just "PAX" decks). You know, like how GitHub's branch dropdown menu has one? Like this: 
![agh](https://user-images.githubusercontent.com/13326489/34661038-db977d72-f414-11e7-91a4-e44693e7973a.png)

**Comment by devgianlu** [comment]
Would be nice, looks a bit difficult to implement.

**Comment by MGageMorgan** [comment]
@devgianlu,

I probably would've said that about this entire project, but it's gone fucking great so far :)

I need to quit procrastinating sleep...

**Comment by MGageMorgan** [comment]
Gahhh my brain won't shut down. 

@devgianlu, IF all of the above comes to fruition, would it be possible to just get rid of the card and put the resulting dropdown in with the ones in the "General" card? That would simplify shit a ton.

**Comment by devgianlu** [comment]
Need to fix #27 first

**Comment by devgianlu** [comment]
I didn't implement the search function because the menu refuses to stay open when the text field gets the focus. Closing anyway.
