### ISSUE TITLE
Fix Mobile to Stay in the Viewport, and Disable Zooming 

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#32]
Mobile needs to be have content fixed to the width of the viewport - see below for what I'm talking about and trying to prevent.

![screenshot_2018-01-12-19-36-28](https://user-images.githubusercontent.com/13326489/34903631-833904be-f803-11e7-96da-cb3f8bb63089.png)
![screenshot_2018-01-12-19-36-33](https://user-images.githubusercontent.com/13326489/34903632-898e8e42-f803-11e7-8d99-ccd13f57d209.png)
![screenshot_2018-01-12-19-36-45](https://user-images.githubusercontent.com/13326489/34903634-95957796-f803-11e7-9c5e-8b36574be3e5.png)
![screenshot_2018-01-12-19-36-50](https://user-images.githubusercontent.com/13326489/34903635-9aee943e-f803-11e7-8de7-f43b540f7ad0.png)
![screenshot_2018-01-12-19-38-02](https://user-images.githubusercontent.com/13326489/34903636-a07620ac-f803-11e7-91ab-51f9aa9c8397.png)
![screenshot_2018-01-12-19-38-06](https://user-images.githubusercontent.com/13326489/34903637-a571200c-f803-11e7-97cd-74794d5f7eca.png)
![screenshot_2018-01-12-19-38-12](https://user-images.githubusercontent.com/13326489/34903638-a990c264-f803-11e7-873d-fd19029d8379.png)
![screenshot_2018-01-12-19-38-16](https://user-images.githubusercontent.com/13326489/34903640-ac9f853a-f803-11e7-9a3f-e10443a94dcd.png)

**Comment by devgianlu** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_ta
