### ISSUE TITLE
Logout Redirect Somehow Screws This Up...Every...Single...Time...

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#33]
This is fairly irritating: Every time I want to log out, I end up with the pic below. That said, on refresh it loads fine. It looks like a padding or margin issue in CSS somewhere. Could we get it right the first time?

![screenshot from 2018-01-13 04-45-58](https://user-images.githubusercontent.com/13326489/34904928-379d8434-f81d-11e7-9a7e-27615cd938e4.png)

**Comment by devgianlu** [comment]
Pretty strange.

**Comment by devgianlu** [comment]
@MGageMorgan I cannot reproduce this issue.

**Comment by MGageMorgan** [comment]
It happens when I go to press the logout button. I don't know why.

**Comment by MGageMorgan** [comment]
I'll reopen if this continues to be an issue
