### ISSUE TITLE
Inputs Broken on Mobile Chrome

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#35]
@devgianlu,

Google Chrome on mobile doesn't take inputs about 95% of the time. However, Firefox Nightly on Android renders everything, albeit a bit glitchy, but still usable. Chrome, OTOH, will get you in, but none of the buttons do anything for some reason...

**Comment by MGageMorgan** [comment]
I'll reopen if this continues to be an issue

**Comment by MGageMorgan** [comment]
@devgianlu,

I just demoed this for a few people in the Autism group I mentioned - let me reiterate I do not have Autism but I advocate for those who do - and this shit happened from John Sheehan's (the group director's) phone. It was Chrome on a Samsung Note 8, IIRC.

When doing QA, please use your actual phone, and have multiple clients open - I don't know why, but when there is more than two clients open, the pages start acting...weird. CSS didn't load at some point, and I had to restart the server. We need this to work properly, but we also need it to scale lmao.

**Comment by devgianlu** [comment]
Ok so this may be an issue with the server that is very slow to answer.

**Comment by devgianlu** [comment]
@MGageMorgan Is this still a thing?

**Comment by MGageMorgan** [comment]
Not that I'm aware of. Again, I'll re-open if I find otherwise. This is from earlier development of the UI. Thanks for reminding me to close this.
