### ISSUE TITLE
Cards list layout

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/PYX-Reloaded#38]
Doing the cards list layout isn't a simple task as cards might have different heights. So there are two solutions:

- Make all the cards the same height (might have issues with overflowing text and we don't want scrolling cards)
- Use a non CSS approach like https://masonry.desandro.com/

**Comment by MGageMorgan** [comment]
@devgianlu I wonder how Masonry handles the infamous CardCast copypasta "If you or a loved one has been diagnosed with mesothelioma..."
