### ISSUE TITLE
Events/notifications system

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/PYX-Reloaded#42]
We need a way to notify the user of what's happening on the server and in the game. We should have two notification mechanism:
- A semi-persistent which will display the events for an interval of time (10/15 seconds)
- A quick one which will display things like the winner of a round

**Comment by MGageMorgan** [comment]
I'd say toast notifications for simplicity

**Comment by devgianlu** [comment]
https://material.io/components/web/catalog/snackbars/

**Comment by devgianlu** [comment]
Done with 0397e75847b3e3234cc2b631e6199c212aa635c6, c3bb2ad29dcbf8f43813b7062e201fcf919555c6 and 960ca7323ee232e5a7e73cc8b7f517d0dbd2001c.
