### ISSUE TITLE
Make White Cards Wider

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#45]
There are currently scrollbars on the inside of some - doesn't look right.

**Comment by devgianlu** [comment]
Vertical or horizontal scrollbars?

**Comment by MGageMorgan** [comment]
@devgianlu See the attached picture on #46 - some white cards literally have a fucking horizontal scrollbar inside them.

**Comment by devgianlu** [comment]
Cache issue
