### ISSUE TITLE
White Cards: Uniform Top-Down Text 

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#46]
Some of the cards have text that gets fucked up when another card that has more text than the one before it gets added - or some shit like that. @devgianlu, are you able to fix this?

![screenshot from 2018-01-28 20-38-01](https://user-images.githubusercontent.com/13326489/35490675-5bd4cfe8-046f-11e8-852f-d61259807ea0.png)

**Comment by devgianlu** [comment]
By default, the text align to the bottom. Will fix that.
