### ISSUE TITLE
Allow Rounds To Be Played

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#47]
@devgianlu,
This ticket contains the "vital" stuff that needs done in order to have a proper game (for the most part).

- [x] #44 takes priority first. My reasoning here is that the transition to WebSockets will require some changes, possibly ones that will be made as needed. In order to get the other stuff below fixed, we need to make sure that sessions work smoothly. Getting rid of long-poll and full-duplexing all comms will prevent the current fuckery that causes the current game to break (times out because, well, long-poll).
- [ ] Make the white cards selectable
    - [ ] Make it so they can be submitted to the Czar, either via a button or modal (I'd say a button beside the arrow on the "Hand cards" bar, like a checkmark icon or something).
- [ ] Implement interface for the judge to receive selected cards 
- [ ] Implement way to select cards for submission
- [ ] Select a user to be Card Czar/judge
- [ ] Update the Scoreboard in the menu to reflect which user is Czar each round
- [x] #46 
- [x] #48

**Comment by devgianlu** [comment]
This is all already implemented. Should this be marked as a bug?

**Comment by MGageMorgan** [comment]
@devgianlu - There's no way in hell #44 is implemented yet - besides that, having pulled the latest commit from game-dev it's non-responsive on my end. 

I'll check my terminal as requested if I have time by the end of the day tomorrow - I have assignment deadlines and I'm super fucked right now...

**Comment by devgianlu** [comment]
Cache issue
