### ISSUE TITLE
Chat Settings Admin Backend

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#5]
There's this whole thing about chat. We should have an entire settings page for admins to customize chat. I can see options for:

- Removing chat entirely from the view - I view it as unnecessary clutter. 
- Commands - I know people might want commands but not chat. We should have a toggle for commands. 
- Chat and Global Chat should have their own toggles. 

I say this because Elijah and I don't want chat taking up screen estate - when we play, we actually call everyone we play with on Discord. 

Also, because I want to make this site more mobile-friendly, (students have iPhones, so the app is good for Android, buuuut...) I want to be able to remove it completely from view - my purposes for using it are locally with students, but IMHO instead of arguing we should go with a "live and let live" approach with some of these.

**Comment by MGageMorgan** [comment]
@gianlu at a family gathering. Will begin posting more issues when I become available once again.

**Comment by devgianlu** [comment]
All done, opened #77 for chat commands.
