### ISSUE TITLE
Chat Form Issue

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#50]
@devgianlu,
- [x] Same as #49, with the enter key not registering
- [x] Mobile issue: This thing gets super fucked up when used on mobile. Needs investigated.

**Comment by devgianlu** [comment]
Looks fine there 

![s80129-074729](https://user-images.githubusercontent.com/14827249/35497384-470d6e48-04ca-11e8-913a-1657287564f0.jpg)
![s80129-074722](https://user-images.githubusercontent.com/14827249/35497385-47391ef8-04ca-11e8-9df4-2aa66253022a.jpg)

**Comment by MGageMorgan** [comment]
@devgianlu - that second one. The "Message" thing goes wayyy above the box...

**Comment by devgianlu** [comment]
Oh yeah I got it
