### ISSUE TITLE
Unable to play Blank Cards

### ISSUE THREAD

**Issue by EpicnessTwo** [devgianlu/PYX-Reloaded#61]
When trying to play a blank card, the game throws an error saying the card can't be played.

**Comment by devgianlu** [comment]
If you could provide some logs (see Developer Tools for Chrome) that would useful. Anyway I've improved the error messages in version 0.0.2, let me know if anything changes.

**Comment by MGageMorgan** [comment]
@devgianlu Yeah, weird shit happened when my friends John and Theo plus myself tried playing. Ugghh don't know if it was a me problem or the server. My network connection was weird

**Comment by devgianlu** [comment]
Remember to clear the cache, all these frequent changes may be messing everything up.

**Comment by EpicnessTwo** [comment]
![21bd1d212bb](https://user-images.githubusercontent.com/7784589/36078545-db77aed6-0f6f-11e8-9600-4a5d03b46f9d.png)

**Comment by devgianlu** [comment]
You have to expand the error message with the little arrows. If you see a key named "responseJSON" that's what I need.

Might need to make logging a little bit clearer so that even non tech people can submit bug reports.

**Comment by EpicnessTwo** [comment]
![image](https://user-images.githubusercontent.com/7784589/36145890-ac735338-10aa-11e8-8335-cd83a8def670.png)
Is this the information you are after?

**Comment by devgianlu** [comment]
This is related to #41. Closing.
