### ISSUE TITLE
Cache handling for new releases

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/PYX-Reloaded#63]
When a new version is released all caches must be cleared. I don't really know how to do that yet.

**Comment by EpicnessTwo** [comment]
An option would be to use a build number as a variable for the query string of things that need to be re-cached. E.G. `cached_file.js?v=0.0.2`

**Comment by devgianlu** [comment]
@EpicnessTwo Nice idea.

**Comment by devgianlu** [comment]
![cache handling](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/images/http-cache-decision-tree.png)

**Comment by devgianlu** [comment]
If think this is the best possible solution for our server that needs the cache to be invalidated immediately. **All users' cache will be invalidated after a server restart.**
