### ISSUE TITLE
Theming Framework

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#7]
We need a less-centralized way to style this. I think individual servers could use some individuality. 

I don't necessarily know the best way to go about this, but if we could make it so it's relatively easy to style everything, it would be great!

**Comment by devgianlu** [comment]
Each user should be able to change it's primary and accent color. Something like [this](https://getmdl.io/customize/index.html). The preferences will then be saved as cookies and in the user's profile when we'll have user acconts.

**Comment by MGageMorgan** [comment]
I really, really, like the idea of that. Not sure how to implement, but we'll cross that bridge when we come to it.
