### ISSUE TITLE
Chat commands

### ISSUE THREAD

**Issue by devgianlu** [devgianlu/PYX-Reloaded#77]
We should make available some commands. To do what? I don't know. 

Commands available to **admins**:
- [x] /ban - To ban someone
- [x] /kick - To kick someone

**Comment by devgianlu** [comment]
@MGageMorgan Which commands may be available?

**Comment by MGageMorgan** [comment]
The only commands we needed on the old one (my friends and I) were for Cardcast. HOWEVER, when we discovered the way your app handled Cardcast, we immediately jumped from that bandwagon and onto the GUI one instead. I would say, as a preliminary measure, for the game creator, kicking and banning and administrative features like such.

**Comment by devgianlu** [comment]
For more commands, create a new issue.
