### ISSUE TITLE
Playing a blank card doesn't hide the card draw.

### ISSUE THREAD

**Issue by EpicnessTwo** [devgianlu/PYX-Reloaded#79]
When you play a blank card, the card draw stays on the screen giving the illusion that the card was never played. Clicking any other card just returns the error "`You have already played all the necessary cards.`".

I'm playing on the latest release

**Comment by devgianlu** [comment]
Based on what you say the issue seems to be on the UI, because the cards get played.

**Comment by devgianlu** [comment]
Hopefully it is fixed, closing until further notice. I should release a new version with the fix in the next hours.
