### ISSUE TITLE
Make Client a PWA!!

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#87]
I think PWAs are dope, so having this will inevitably take some work, but I like the PWA standard over bloated Electron and friends. 

I would spearhead this myself, but I feel like I have too much going on right now. I'll be around lol - I like the work done here tho, keep it up!

**Comment by devgianlu** [comment]
I'll try to comply the PWA standards using a tool from Google called Lighthouse, it detects the major issues with the website.

**Comment by devgianlu** [comment]
Added a manifest file with 8e4d79ca8a8493268b1e2186334cacd2672de601, without the logo.

**Comment by devgianlu** [comment]
Added icon with 088e87a66e3609fdad302666b782285b74f7adaf. For now I've done all that we can do.

**Comment by devgianlu** [comment]
[Lighthouse Report.pdf](https://github.com/devgianlu/PYX-Reloaded/files/1812543/Lighthouse.Report.pdf)
