### ISSUE TITLE
Add A Service Worker for PWA

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#92]
One potentially useful feature: You know the notifs using Noty.js? Do a check to see if the browser has native notification support, and if not, keep Noty.js notifs as a fallback - this is also a good use to have a service worker supposedly instead of having one just because PWAs require it.

**Comment by devgianlu** [comment]
I don't know how to implement a Service Worker. It is useful for caching stuff but we don't have to. Using it for notifications would require another protocol other than WebSocket.
