### ISSUE TITLE
Dynamically Change Theme (yeah, this again)

### ISSUE THREAD

**Issue by MGageMorgan** [devgianlu/PYX-Reloaded#93]
This is a minor issue but inconsistency is notable - instead of manual refreshing, this should be taken care of dynamically.
![screenshot_2018-03-15-23-57-33](https://user-images.githubusercontent.com/13326489/37504550-6df89064-28b5-11e8-840e-3494eff41e81.png)
![screenshot_2018-03-16-00-00-06](https://user-images.githubusercontent.com/13326489/37504561-869dd0de-28b5-11e8-9be1-b019e7f0b53a.png)

**Comment by devgianlu** [comment]
https://stackoverflow.com/a/33193739/5446197?stw=2
